/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.admin.actions;

import client.admin.AdminOptions;
import data.PersonData;
import domains.Password;
import entities.Person;

import java.awt.Color;
import java.io.IOException;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author whala
 */
public class CadastroForm extends JFrame {

    /**
     * Creates new form Cadastro_Form
     */
    public CadastroForm() {
        initComponents();
        
        Border jPanel_title_border = BorderFactory.createMatteBorder(0, 1, 1, 1, Color.gray);
        jPanel_title.setBorder(jPanel_title_border);

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_fechar.setBorder(label_border);
        
        this.setLocationRelativeTo(null);
        
        Border field_border = BorderFactory.createMatteBorder(1, 5, 1, 1, Color.white);
        jTextField_Nome.setBorder(field_border);
        jTextField_CPF.setBorder(field_border);
        jTextField_Idade.setBorder(field_border);
        jTextField_Email.setBorder(field_border);
        jTextField_Logradouro.setBorder(field_border);
        jTextField_Numero.setBorder(field_border);
        jTextField_Bairro.setBorder(field_border);
        jTextField_Cidade.setBorder(field_border);
        jTextField_Estado.setBorder(field_border);
        jTextField_CEP.setBorder(field_border);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_healthPosition1);
        bg.add(jRadioButton_healthPosition2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        buttonGroup3 = new ButtonGroup();
        buttonGroup4 = new ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_Cadastrar = new javax.swing.JButton();
        jLabel_Nome = new javax.swing.JLabel();
        jLabel_CPF = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Logradouro = new javax.swing.JLabel();
        jLabel_Numero = new javax.swing.JLabel();
        jLabel_Bairro = new javax.swing.JLabel();
        jLabel_Cidade = new javax.swing.JLabel();
        jLabel_Idade = new javax.swing.JLabel();
        jLabel_Estado = new javax.swing.JLabel();
        jLabel_CEP = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jTextField_CPF = new javax.swing.JTextField();
        jTextField_Idade = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Logradouro = new javax.swing.JTextField();
        jTextField_Numero = new javax.swing.JTextField();
        jTextField_Bairro = new javax.swing.JTextField();
        jTextField_Cidade = new javax.swing.JTextField();
        jTextField_Estado = new javax.swing.JTextField();
        jTextField_CEP = new javax.swing.JTextField();
        jLabel_Saude = new javax.swing.JLabel();
        jRadioButton_healthPosition1 = new javax.swing.JRadioButton();
        jLabel_Usuario = new javax.swing.JLabel();
        jComboBox_Usuario = new javax.swing.JComboBox<>();
        jRadioButton_healthPosition2 = new javax.swing.JRadioButton();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_fechar = new javax.swing.JLabel();
        jPanel_title = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_logo = new javax.swing.JLabel();

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setText("jTextField2");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setText("jTextField2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new Color(204, 255, 204));

        jPanel2.setBackground(new Color(255, 255, 255));

        jButton_Cadastrar.setBackground(new Color(235, 47, 6));
        jButton_Cadastrar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jButton_Cadastrar.setForeground(new Color(255, 255, 255));
        jButton_Cadastrar.setText("Cadastrar");
        jButton_Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CadastrarMouseExited(evt);
            }
        });
        jButton_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton_CadastrarActionPerformed(evt);
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel_Nome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Nome.setText("Nome:");

        jLabel_CPF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_CPF.setText("CPF:");

        jLabel_Email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Email.setText("Email:");

        jLabel_Logradouro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Logradouro.setText("Logradouro:");

        jLabel_Numero.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Numero.setText("Número:");

        jLabel_Bairro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Bairro.setText("Bairro:");

        jLabel_Cidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Cidade.setText("Cidade:");

        jLabel_Idade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Idade.setText("Idade:");

        jLabel_Estado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Estado.setText("Estado:");

        jLabel_CEP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_CEP.setText("CEP:");

        jTextField_Nome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_Nome.setForeground(new Color(153, 153, 153));
        jTextField_Nome.setText("nome");
        jTextField_Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NomeFocusLost(evt);
            }
        });

        jTextField_CPF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_CPF.setForeground(new Color(153, 153, 153));
        jTextField_CPF.setText("CPF sem caracteres especiais");
        jTextField_CPF.setPreferredSize(new java.awt.Dimension(93, 28));
        jTextField_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_CPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_CPFFocusLost(evt);
            }
        });

        jTextField_Idade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_Idade.setForeground(new Color(153, 153, 153));
        jTextField_Idade.setText("20,57,89...");
        jTextField_Idade.setPreferredSize(new java.awt.Dimension(93, 28));
        jTextField_Idade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_IdadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_IdadeFocusLost(evt);
            }
        });
        jTextField_Idade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IdadeKeyTyped(evt);
            }
        });

        jTextField_Email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_Email.setForeground(new Color(153, 153, 153));
        jTextField_Email.setText("maria@email.com");
        jTextField_Email.setPreferredSize(new java.awt.Dimension(93, 28));
        jTextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusLost(evt);
            }
        });

        jTextField_Logradouro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_Logradouro.setForeground(new Color(153, 153, 153));
        jTextField_Logradouro.setText("rua luis gonzaga");
        jTextField_Logradouro.setPreferredSize(new java.awt.Dimension(93, 28));
        jTextField_Logradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_LogradouroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LogradouroFocusLost(evt);
            }
        });

        jTextField_Numero.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_Numero.setForeground(new Color(153, 153, 153));
        jTextField_Numero.setText("789");
        jTextField_Numero.setPreferredSize(new java.awt.Dimension(93, 28));
        jTextField_Numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NumeroFocusLost(evt);
            }
        });
        jTextField_Numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NumeroKeyTyped(evt);
            }
        });

        jTextField_Bairro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_Bairro.setForeground(new Color(153, 153, 153));
        jTextField_Bairro.setText("guanabara");
        jTextField_Bairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_BairroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_BairroFocusLost(evt);
            }
        });

        jTextField_Cidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_Cidade.setForeground(new Color(153, 153, 153));
        jTextField_Cidade.setText("canoas");
        jTextField_Cidade.setPreferredSize(new java.awt.Dimension(93, 28));
        jTextField_Cidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_CidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_CidadeFocusLost(evt);
            }
        });

        jTextField_Estado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_Estado.setForeground(new Color(153, 153, 153));
        jTextField_Estado.setText("sao paulo");
        jTextField_Estado.setPreferredSize(new java.awt.Dimension(93, 28));
        jTextField_Estado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_EstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EstadoFocusLost(evt);
            }
        });

        jTextField_CEP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_CEP.setForeground(new Color(153, 153, 153));
        jTextField_CEP.setText("CEP apenas com numeros");
        jTextField_CEP.setPreferredSize(new java.awt.Dimension(93, 28));
        jTextField_CEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_CEPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_CEPFocusLost(evt);
            }
        });
        jTextField_CEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CEPKeyTyped(evt);
            }
        });

        jLabel_Saude.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Saude.setText("O paciente trabalha na área da saúde?");

        jRadioButton_healthPosition1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_healthPosition1.setSelected(true);
        jRadioButton_healthPosition1.setText("Sim");

        jLabel_Usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_Usuario.setText("Usuario");

        jComboBox_Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Atendente", "Paciente" }));
        jComboBox_Usuario.setMinimumSize(new java.awt.Dimension(93, 28));

        jRadioButton_healthPosition2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_healthPosition2.setText("Não");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_Estado)
                        .addGap(61, 61, 61)
                        .addComponent(jTextField_Estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_Cidade)
                        .addGap(60, 60, 60)
                        .addComponent(jTextField_Cidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CPF)
                            .addComponent(jLabel_Nome)
                            .addComponent(jLabel_Idade)
                            .addComponent(jLabel_Logradouro))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Logradouro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Idade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Nome)
                            .addComponent(jTextField_CPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Numero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Bairro, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_CEP)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_CEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Email))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Numero))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Bairro))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Saude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_healthPosition1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_healthPosition2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nome)
                    .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CPF)
                    .addComponent(jTextField_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Idade)
                    .addComponent(jTextField_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Email)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Logradouro)
                    .addComponent(jTextField_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Numero)
                    .addComponent(jTextField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Bairro)
                    .addComponent(jTextField_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cidade)
                    .addComponent(jTextField_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Estado)
                    .addComponent(jTextField_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CEP)
                    .addComponent(jTextField_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton_healthPosition1)
                        .addComponent(jRadioButton_healthPosition2))
                    .addComponent(jLabel_Saude, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel_minimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_fechar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_fechar.setText(" x");
        jLabel_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_fecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_fecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_fecharMouseExited(evt);
            }
        });

        jPanel_title.setBackground(new Color(204, 255, 204));

        jLabel3.setBackground(new Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Cadastro");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_minimize)
                        .addComponent(jLabel_fechar))
                    .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/img_covid2.jpg")));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CadastrarMouseEntered
        jButton_Cadastrar.setBackground(new Color(225,20,2));

    }//GEN-LAST:event_jButton_CadastrarMouseEntered

    private void jButton_CadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CadastrarMouseExited
        jButton_Cadastrar.setBackground(new Color(235,47,6));

    }//GEN-LAST:event_jButton_CadastrarMouseExited

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.gray);
        
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.black);
        
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_fecharMouseClicked
        AdminOptions lgf = new AdminOptions();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jLabel_fecharMouseClicked

    private void jLabel_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_fecharMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        jLabel_fechar.setBorder(label_border);
        jLabel_fechar.setForeground(Color.red);
        
    }//GEN-LAST:event_jLabel_fecharMouseEntered

    private void jLabel_fecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_fecharMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_fechar.setBorder(label_border);
        jLabel_fechar.setForeground(Color.black);
        
    }//GEN-LAST:event_jLabel_fecharMouseExited

    private void jTextField_NomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NomeFocusGained
        if(jTextField_Nome.getText().trim().toLowerCase().equals("nome")) {
            jTextField_Nome.setText("");
            jTextField_Nome.setForeground(Color.black);
            
        }        
    }//GEN-LAST:event_jTextField_NomeFocusGained

    private void jTextField_NomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NomeFocusLost
        if(jTextField_Nome.getText().trim().equals("") || 
           jTextField_Nome.getText().trim().toLowerCase().equals("nome")) {
            jTextField_Nome.setText("nome");
            jTextField_Nome.setForeground(new Color(153,153,153));
            
        }  
    }//GEN-LAST:event_jTextField_NomeFocusLost

    private void jTextField_CPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CPFFocusGained
        if(jTextField_CPF.getText().trim().toLowerCase().equals("cpf sem caracteres especiais")){
            jTextField_CPF.setText("");
            jTextField_CPF.setForeground(Color.black);
            
        }        
    }//GEN-LAST:event_jTextField_CPFFocusGained

    private void jTextField_CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CPFFocusLost
        if(jTextField_CPF.getText().trim().equals("") || 
           jTextField_CPF.getText().trim().toLowerCase().equals("cpf sem caracteres especiais")) {
            jTextField_CPF.setText("cpf sem caracteres especiais");
            jTextField_CPF.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_CPFFocusLost

    private void jTextField_IdadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_IdadeFocusGained
        if(jTextField_Idade.getText().trim().toLowerCase().equals("20,57,89...")){
            jTextField_Idade.setText("");
            jTextField_Idade.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextField_IdadeFocusGained

    private void jTextField_IdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_IdadeFocusLost
        if(jTextField_Idade.getText().trim().equals("") || 
           jTextField_Idade.getText().trim().toLowerCase().equals("20,57,89...")) {
            jTextField_Idade.setText("20,57,89...");
            jTextField_Idade.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_IdadeFocusLost

    private void jTextField_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusGained
        if(jTextField_Email.getText().trim().toLowerCase().equals("maria@email.com")){
            jTextField_Email.setText("");
            jTextField_Email.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextField_EmailFocusGained

    private void jTextField_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusLost
        if(jTextField_Email.getText().trim().equals("") || 
           jTextField_Email.getText().trim().toLowerCase().equals("maria@email.com")) {
            jTextField_Email.setText("maria@email.com");
            jTextField_Email.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_EmailFocusLost

    private void jTextField_LogradouroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LogradouroFocusGained
        if(jTextField_Logradouro.getText().trim().toLowerCase().equals("rua luis gonzaga")){
            jTextField_Logradouro.setText("");
            jTextField_Logradouro.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextField_LogradouroFocusGained

    private void jTextField_LogradouroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LogradouroFocusLost
        if(jTextField_Logradouro.getText().trim().equals("") || 
           jTextField_Logradouro.getText().trim().toLowerCase().equals("rua luis gonzaga")) {
            jTextField_Logradouro.setText("rua luis gonzaga");
            jTextField_Logradouro.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_LogradouroFocusLost

    private void jTextField_NumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NumeroFocusGained
        if(jTextField_Numero.getText().trim().toLowerCase().equals("789")){
            jTextField_Numero.setText("");
            jTextField_Numero.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextField_NumeroFocusGained

    private void jTextField_NumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NumeroFocusLost
        if(jTextField_Numero.getText().trim().equals("") || 
           jTextField_Numero.getText().trim().toLowerCase().equals("789")) {
            jTextField_Numero.setText("789");
            jTextField_Numero.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_NumeroFocusLost

    private void jTextField_BairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_BairroFocusGained
        if(jTextField_Bairro.getText().trim().toLowerCase().equals("guanabara")){
            jTextField_Bairro.setText("");
            jTextField_Bairro.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextField_BairroFocusGained

    private void jTextField_BairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_BairroFocusLost
        if(jTextField_Bairro.getText().trim().equals("") || 
           jTextField_Bairro.getText().trim().toLowerCase().equals("guanabara")) {
            jTextField_Bairro.setText("guanabara");
            jTextField_Bairro.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_BairroFocusLost

    private void jTextField_CidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CidadeFocusGained
        if(jTextField_Cidade.getText().trim().toLowerCase().equals("canoas")){
            jTextField_Cidade.setText("");
            jTextField_Cidade.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextField_CidadeFocusGained

    private void jTextField_CidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CidadeFocusLost
        if(jTextField_Cidade.getText().trim().equals("") || 
           jTextField_Cidade.getText().trim().toLowerCase().equals("canoas")) {
            jTextField_Cidade.setText("canoas");
            jTextField_Cidade.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_CidadeFocusLost

    private void jTextField_EstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EstadoFocusGained
        if(jTextField_Estado.getText().trim().toLowerCase().equals("sao paulo")){
            jTextField_Estado.setText("");
            jTextField_Estado.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextField_EstadoFocusGained

    private void jTextField_EstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EstadoFocusLost
        if(jTextField_Estado.getText().trim().equals("") || 
           jTextField_Estado.getText().trim().toLowerCase().equals("sao paulo")) {
            jTextField_Estado.setText("sao paulo");
            jTextField_Estado.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_EstadoFocusLost

    private void jTextField_CEPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CEPFocusGained
        if(jTextField_CEP.getText().trim().toLowerCase().equals("cep apenas com numeros")){
            jTextField_CEP.setText("");
            jTextField_CEP.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextField_CEPFocusGained

    private void jTextField_CEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CEPFocusLost
        if(jTextField_CEP.getText().trim().equals("") || 
           jTextField_CEP.getText().trim().toLowerCase().equals("cep apenas com numeros")) {
            jTextField_CEP.setText("cep apenas com numeros");
            jTextField_CEP.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_jTextField_CEPFocusLost

    private void jTextField_IdadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdadeKeyTyped
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextField_IdadeKeyTyped

    private void jTextField_NumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NumeroKeyTyped
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextField_NumeroKeyTyped

    private void jTextField_CEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CEPKeyTyped
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextField_CEPKeyTyped

    public void jButton_CadastrarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, IOException {
        PersonData insert = new PersonData();
        Password pass = new Password();

        String cpf = jTextField_CPF.getText();
        String name = jTextField_Nome.getText();
        int age = Integer.parseInt(jTextField_Idade.getText());
        String email = jTextField_Email.getText();
        String address = jTextField_Logradouro.getText();
        int addressNumber =  Integer.parseInt(jTextField_Numero.getText());
        String district = jTextField_Bairro.getText();
        String city = jTextField_Cidade.getText();
        String state = jTextField_Estado.getText();
        int cep = Integer.parseInt(jTextField_CEP.getText());
        boolean healthPosition = true;
        int priority = 3;

        if (jRadioButton_healthPosition2.isSelected()) {
            healthPosition = false;
        }
        int perfil = jComboBox_Usuario.getSelectedIndex()+1;
        if (perfil == 3){
            if(healthPosition){
                priority = 2;
            }
            if(age>=70){
                priority = 1;
            }
            Person p = new Person( name,  cpf,  age,  email, address,  addressNumber,  state,  city,  district,  cep,  healthPosition,  priority);
            insert.insertPerson(p);
            return;
        }
        String password = pass.createPassword(email);

        Person p = new Person(name,  cpf, age,  email,  password, address,
        addressNumber,  state,  city,  district,  cep,
         perfil,  healthPosition,  priority);

        insert.insertPerson(p);
        return;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private ButtonGroup buttonGroup2;
    private ButtonGroup buttonGroup3;
    private ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton_Cadastrar;
    private javax.swing.JComboBox<String> jComboBox_Usuario;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Bairro;
    private javax.swing.JLabel jLabel_CEP;
    private javax.swing.JLabel jLabel_CPF;
    private javax.swing.JLabel jLabel_Cidade;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Estado;
    private javax.swing.JLabel jLabel_Idade;
    private javax.swing.JLabel jLabel_Logradouro;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Numero;
    private javax.swing.JLabel jLabel_Saude;
    private javax.swing.JLabel jLabel_Usuario;
    private javax.swing.JLabel jLabel_fechar;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JRadioButton jRadioButton_healthPosition1;
    private javax.swing.JRadioButton jRadioButton_healthPosition2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField_Bairro;
    private javax.swing.JTextField jTextField_CEP;
    private javax.swing.JTextField jTextField_CPF;
    private javax.swing.JTextField jTextField_Cidade;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Estado;
    private javax.swing.JTextField jTextField_Idade;
    private javax.swing.JTextField jTextField_Logradouro;
    private javax.swing.JTextField jTextField_Nome;
    private javax.swing.JTextField jTextField_Numero;
    // End of variables declaration//GEN-END:variables
}
